name: bnn-bo
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex
  #- _openmp_mutex
  - asttokens
  - backcall
  - ca-certificates
  - debugpy
  - decorator
  - entrypoints
  - executing
  - ipykernel
  - ipython
  - jedi
  - jupyter_client
  - jupyter_core
  - ld_impl_linux-64
  - libffi
  #- libgcc-ng
  #- libgomp
  - libsodium
  #- libstdcxx-ng
  - matplotlib-inline
  - ncurses
  - nest-asyncio
  - openssl
  - packaging
  - parso
  - pcre
  - pexpect
  - pickleshare
  - pip
  - prompt-toolkit
  - ptyprocess
  - pure_eval
  - pygments
  - python
  - python-dateutil
  - python_abi
  - pyzmq
  - readline
  - setuptools
  - six
  - sqlite
  - stack_data
  - tk
  - tornado
  - traitlets
  - typing_extensions
  - tzdata
  - wcwidth
  - wheel
  - xz
  - zeromq
  - zlib
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu116
      - asdfghjkl
      - backpack-for-pytorch
      - blessed
      - botorch
      - box2d-py
      - certifi
      - charset-normalizer
      - cloudpickle
      - cmake
      - contourpy
      - cycler
      - einops
      - emcee
      - filelock
      - fonttools
      - gpustat
      - gpytorch
      - gym
      - gym-notices
      - idna
      - importlib-metadata
      - importlib-resources
      - jinja2
      - joblib
      - kiwisolver
      - laplace-torch
      - linear-operator
      - lit
      - llvmlite
      - markupsafe
      - matplotlib
      - mpmath
      - multipledispatch
      - networkx
      - numba
      - numpy
      #- nvidia-cublas-cu11
      # - nvidia-cuda-cupti-cu11
      # - nvidia-cuda-nvrtc-cu11
      #- nvidia-cuda-runtime-cu11
      # - nvidia-cudnn-cu11
      # - nvidia-cufft-cu11
      # - nvidia-curand-cu11
      # - nvidia-cusolver-cu11
      # - nvidia-cusparse-cu11
      # - nvidia-ml-py
      # - nvidia-nccl-cu11
      #- nvidia-nvtx-cu11
      - opencv-python
      - opt-einsum
      - pillow
      - psutil
      - py-pde
      - pygame
      - pyparsing
      - requests
      - scikit-learn
      - scipy
      - swig
      - sympy
      - threadpoolctl
      - torch
      - torchaudio
      - torchvision
      - tqdm
      #- triton
      - urllib3
      - zipp